# Generated by Django 5.1 on 2024-09-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_username'),
        ('accounts', '0004_alter_medicalrecord_doctor_and_more'),
    ]

    operations = [
    ]
